name: skybuildz
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/CircularStd-Medium.ttf
        - asset: assets/fonts/CircularAir-Light.ttf
          weight: 100
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 500
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf


